### PR TITLE
Upload the current frame instead of the previous one to the frontend

### PR DESCRIPTION
**Pull request by realnc**
Reduces input lag by 1 frame.

---------

Basically, the frontend was constantly running 1 frame behind the emulator. This fixes it.

### CODE REVIEW

**Comment by sonninnos** [comment]
Thanks! Indeed it does. Confirmed with JoyTest & pause+frame advancing.

Now just have to figure out how to stop the statusbar and vkbd from flickering.

**Comment by realnc** [comment]
> Now just have to figure out how to stop the statusbar and vkbd from flickering.

Hm. Right. For the statusbar, it needs to be drawn after the emulator runs but before uploading the frame:

```diff
diff --git a/libretro/libretro.c b/libretro/libretro.c
index c53d517..e4c4978 100644
--- a/libretro/libretro.c
+++ b/libretro/libretro.c
@@ -2774,10 +2774,10 @@ void retro_run(void)
    }
 
    retro_poll_event();
-   if (STATUSON==1) Print_Status();
 
 sortie:
    co_switch(emuThread);
+   if (STATUSON==1) Print_Status();
    video_cb(bmp, retrow, zoomed_height, retrow << (pix_bytes / 2));
 }
```

**Comment by sonninnos** [comment]
VKBD seems to be ok with this:
```
diff --git a/libretro/libretro-mapper.c b/libretro/libretro-mapper.c
index 669b0d0..bc9f63b 100644
--- a/libretro/libretro-mapper.c
+++ b/libretro/libretro-mapper.c
@@ -61,6 +61,7 @@ extern int pix_bytes;
 extern bool fake_ntsc;
 extern bool real_ntsc;

+int vkx=0,vky=0;
 int vkflag[7]={0};
 static int jflag[4][16]={0};
 static int kjflag[2][16]={0};
@@ -755,7 +756,6 @@ void update_input(int disable_physical_cursor_keys)

    static int i, j, mk;
    static int oldi=-1;
-   static int vkx=0,vky=0;

    static int LX, LY, RX, RY;
    static int threshold=20000;
@@ -1071,8 +1071,6 @@ void update_input(int disable_physical_cursor_keys)
       else if (vky > NLIGN-1)
          vky=0;

-      virtual_kbd(bmp,vkx,vky);
-
       /* Position toggle, RetroPad X */
       i=RETRO_DEVICE_ID_JOYPAD_X;
       if (vkflag[6]==0 && (input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, i) || input_state_cb(1, RETRO_DEVICE_JOYPAD, 0, i)))
diff --git a/libretro/libretro.c b/libretro/libretro.c
index 6d37067..56acc63 100644
--- a/libretro/libretro.c
+++ b/libretro/libretro.c
@@ -69,6 +69,9 @@ extern unsigned short int bmp[EMULATOR_MAX_WIDTH*EMULATOR_MAX_HEIGHT];
 extern unsigned short int savebmp[EMULATOR_MAX_WIDTH*EMULATOR_MAX_HEIGHT];
 extern int SHIFTON;
 extern int STATUSON;
+extern int SHOWKEY;
+extern int vkx;
+extern int vky;
 extern char RPATH[512];
 extern void Print_Status(void);
 static int firstpass = 1;
@@ -2774,11 +2777,12 @@ void retro_run(void)
    }

    retro_poll_event();
-   if (STATUSON==1) Print_Status();

 sortie:
-   video_cb(bmp, retrow, zoomed_height, retrow << (pix_bytes / 2));
    co_switch(emuThread);
+   if (STATUSON==1) Print_Status();
+   if (SHOWKEY==1) virtual_kbd(bmp,vkx,vky);
+   video_cb(bmp, retrow, zoomed_height, retrow << (pix_bytes / 2));
 }

 #define ADF_FILE_EXT "adf"
```

**Comment by realnc** [comment]
I'm currently adding a more "proper" way without introducing more globals.

**Comment by sonninnos** [comment]
Nice. Looks like I found a way to get one frame off from VICE by relocating `retro_poll_event()`! Thanks again for the nudge!

**Comment by rsn8887** [comment]
Shall I merge now, or wait, @realnc ? Because of your comment, it sounds like you are still working on this?

**Comment by realnc** [comment]
I tried to do some minor refactoring in order to introduce more global variables, but the current code is not very friendly to that. One small change requires another larger one, which requires a yet larger one...

So I just used your approach and added the globals (with longer names in order avoid possible conflicts.)

So, merge.

**Comment by rsn8887** [comment]
Awesome! Thanks.

**Pull request merged**
