### PR TITLE
CD32 support

### LINKED ISSUE #145: Is Amiga CD32 support planned for this core (running iso/cue files)?
I've read through the Issue tracker here (both the closed ones and those that are open), and I've read through the readme-file on this github page for this libretro core. I didn't find any info regarding Amiga CD32 support, other than maybe CD32 support via whdload/hdf files.

Are there any plans for adding Amiga CD32 support in the future for this libretro core, and by that making it possible to run CD32 games through various CD-formats (iso/cue and so on)?

### PR DESCRIPTION
**Pull request by sonninnos**
- Kickstart + Extended ROM info in README
- Model will autochange to CD32 with CD images (ISO/CUE/CCD/NRG)
- Controller type needs to be set manually to CD32 (no way to change the default only with CD32?)
- Flash RAMs (NVRAM) created per game to RA/saves/
  - NVRAM load/save indicator in statusbar

Closes #145 

Bonus:
+ Audio core options show/hide, hidden by default
+ Video core options show/hide, hidden by default
+ Allowed extra RetroPad mappings also in CD32 pad mode
+ Default statusbar toggle key to F12

Minor todo:
- CHD images
- Eject works, Reinsert+Append nopes

### CODE REVIEW

**Comment by sonninnos** [comment]
Sorry for the whack-a-mole, only tested with Windows. And I don't get any of these:
```
sources/src/blkdev.c: In function 'getsem2':
sources/src/blkdev.c:268:18: error: invalid operands to binary == (have 'uae_sem_t {aka struct <anonymous>}' and 'void *')
     if (st->sema == NULL)
         ~~~~~~~~ ^~
sources/src/blkdev.c: In function 'sys_command_close_internal':
sources/src/blkdev.c:310:12: error: incompatible types when assigning to type 'uae_sem_t {aka struct <anonymous>}' from type 'void *'
   st->sema = NULL;
            ^
sources/src/blkdev.c: In function 'sys_command_open_internal':
sources/src/blkdev.c:318:15: error: invalid operands to binary == (have 'uae_sem_t {aka struct <anonymous>}' and 'void *')
  if (st->sema == NULL)
      ~~~~~~~~ ^~
sources/src/blkdev.c: In function 'check_changes':
sources/src/blkdev.c:607:7: error: used struct type value where scalar is required
   if (st->sema)
       ^~
sources/src/blkdev.c:646:6: error: used struct type value where scalar is required
  if (st->sema)
      ^~
```

**Comment by rsn8887** [comment]
I just need to test this on Switch. Once I tested it and verified it works on Switch, I will merge.

**Comment by rsn8887** [comment]
I am just getting a hand on endless black screen when trying to start CD32 on Switch, with game or without. Menu cannot be brought up.

**Comment by rsn8887** [comment]
Log starting core with all default options but model set to CD32:
https://pastebin.com/TR75Cd4B

Log starting core with all default options:
https://pastebin.com/zUmidkDB

**Comment by rsn8887** [comment]
Better logs
Starting core, default config but model: CD32:
```
[INFO] [config] loading config from: /retroarch/retroarch.cfg.
[libretro-uae]: Generating temporary config file '/retroarch/cores/savefiles/puae_libretro.uae'
[libretro-uae]: Booting default configuration
[libretro-uae]: Resolution selected: 720x574
[libretro-uae]: Controller 1: RetroPad
[libretro-uae]: Controller 2: RetroPad
[libretro-uae]: Controller 3: RetroPad
[libretro-uae]: Controller 4: RetroPad
------------------------------------------------------------------------------------
P-UAE 2.6.1
Git Commit: 0186c1b16f7181ffa02d73e6920d3180ce457c46
Build date: Dec 17 2019 16:06:56
------------------------------------------------------------------------------------
Copyright 1995-2002 Bernd Schmidt
          1999-2013 Toni Wilen
          2003-2007 Richard Drummond
          2006-2013 Mustafa 'GnoStiC' Tufan

See the source for a full list of contributors.
This is free software; see the file COPYING for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
------------------------------------------------------------------------------------
Opening cfgfile '/retroarch/cores/savefiles/puae_libretro.uae': OK
Known ROM 'CD32 KS ROM v3.1' loaded
No disk in drive 0.
CPU cycleunit: 128 (0.250)
Building CPU table for configuration: 68020 ~cycle-exact 24-bit
1883 CPU functions
Building CPU, 45954 opcodes (2 -1 1)
CPU=68020, FPU=0, MMU=0, JIT=CPU=0.
CPU cycleunit: 128 (0.250)
Reset at 00000000. Chipset mask = 00000007
00000000    2048K/1 =    2048K Chip memory
00200000    8704K/0 =    8704K <none>
00A80000     512K/1 =     512K Kickstart ROM (1E62D4A5)
=CD32 KS ROM v3.1 rev 40.60 (512k)
00B00000     512K/1 =     512K Extended Kickstart ROM (87746BE2)
=CD32 extended ROM rev 40.60 (512k)
00B80000      64K/0 =      64K Akiko
00B90000     384K/0 =     384K <none>
00BF0000      64K/0 =      64K CIA
00C00000    1792K/0 =    1792K <none>
00DC0000      64K/0 =      64K Battery backed up clock (none)
00DD0000     128K/0 =     128K Gayle (high)
00DF0000      64K/0 =      64K Custom chipset
00E00000     512K/1 =     512K Extended Kickstart ROM (87746BE2)
=CD32 extended ROM rev 40.60 (512k)
00E80000      64K/0 =      64K Autoconfig
00E90000     960K/0 =     960K <none>
00F80000     512K/1 =     512K Kickstart ROM (1E62D4A5)
=CD32 KS ROM v3.1 rev 40.60 (512k)
Image driver open.
IMAGE driver installed, ok=1
```
then hang on endless black screen, menu cannot be activated anymore.



For comparison, starting core with default config:
```
[INFO] [config] loading config from: /retroarch/retroarch.cfg.
[libretro-uae]: Generating temporary config file '/retroarch/cores/savefiles/puae_libretro.uae'
[libretro-uae]: Booting default configuration
[libretro-uae]: Resolution selected: 720x574
[libretro-uae]: Controller 1: RetroPad
[libretro-uae]: Controller 2: RetroPad
[libretro-uae]: Controller 3: RetroPad
[libretro-uae]: Controller 4: RetroPad
------------------------------------------------------------------------------------
P-UAE 2.6.1
Git Commit: 0186c1b16f7181ffa02d73e6920d3180ce457c46
Build date: Dec 17 2019 16:06:56
------------------------------------------------------------------------------------
Copyright 1995-2002 Bernd Schmidt
          1999-2013 Toni Wilen
          2003-2007 Richard Drummond
          2006-2013 Mustafa 'GnoStiC' Tufan

See the source for a full list of contributors.
This is free software; see the file COPYING for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
------------------------------------------------------------------------------------
Opening cfgfile '/retroarch/cores/savefiles/puae_libretro.uae': OK
Known ROM 'KS ROM v1.3 (A500,A1000,A2000)' loaded
No disk in drive 0.
CPU cycleunit: 256 (0.500)
Building CPU table for configuration: 68000 prefetch and cycle-exact 24-bit
1883 CPU functions
Building CPU, 44316 opcodes (0 -1 1)
CPU=68000, FPU=0, MMU=0, JIT=CPU=0.
CPU cycleunit: 256 (0.500)
Reset at 00000000. Chipset mask = 00000000
00000000    2048K/4 =     512K Chip memory
00200000    8192K/0 =    8192K <none>
00A00000    2048K/0 =    2048K CIA
00C00000     512K/1 =     512K Slow memory
00C80000    1024K/0 =    1024K Custom chipset
00D80000     256K/0 =     256K <none>
00DC0000      64K/0 =      64K Battery backed up clock (none)
00DD0000      64K/0 =      64K <none>
00DE0000     128K/0 =     128K Custom chipset
00E00000     512K/2 =     256K Kickstart ROM (C4F0F55F)
=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
00E80000      64K/0 =      64K Autoconfig
00E90000     960K/0 =     960K <none>
00F80000     512K/2 =     256K Kickstart ROM (C4F0F55F)
=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
PAL mode V=49.9201Hz H=15625.0881Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
hardreset, memory cleared
PAL mode V=49.9201Hz H=15625.0881Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
Illegal instruction: 4e7b at 00FC0564 -> 00FC0582
```

**Comment by rsn8887** [comment]
We could disable CD32 on Switch for now somehow, and merge. Or try to debug.

**Comment by rsn8887** [comment]
The error might also happen in Yuzu Switch emulator, not sure. Might make debugging easier if it happens in the emulator.

**Comment by sonninnos** [comment]
This is how it should go:
```
Image driver open.
IMAGE driver installed, ok=1
using drive IMG:<EMPTY> (unit 0, media 0)
CD32: media changed = 0
PAL mode V=49.9201Hz H=15625.0881Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
hardreset, memory cleared
PAL mode V=49.9201Hz H=15625.0881Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
6888x no FPU: f201 00009000 PC=00f80cac
B-Trap f201 at f80cac (0000000015D620CC)
```

Please try if there is any difference now, thanks.

**Comment by rsn8887** [comment]
I don't have my Switch atm, but compiling this latest source for osx causes a crash even starting default A500 config. Latest buildbot core from 20191219 works fine.

OSX log:
```
[libretro-uae]: Generating temporary config file '/Users/arne/Documents/RetroArch/saves/puae_libretro.uae'
[libretro-uae]: Booting default configuration
[libretro-uae]: Resolution selected: 720x574
[libretro-uae]: Controller 1: RetroPad
[libretro-uae]: Controller 2: RetroPad
[libretro-uae]: Controller 3: RetroPad
[libretro-uae]: Controller 4: RetroPad
------------------------------------------------------------------------------------
P-UAE 2.6.1
Git Commit: 0186c1b16f7181ffa02d73e6920d3180ce457c46
Build date: Dec 19 2019 10:48:07
------------------------------------------------------------------------------------
Copyright 1995-2002 Bernd Schmidt
          1999-2013 Toni Wilen
          2003-2007 Richard Drummond
          2006-2013 Mustafa 'GnoStiC' Tufan

See the source for a full list of contributors.
This is free software; see the file COPYING for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
------------------------------------------------------------------------------------
Opening cfgfile '/Users/arne/Documents/RetroArch/saves/puae_libretro.uae': OK
Known ROM 'KS ROM v1.3 (A500,A1000,A2000)' loaded
No disk in drive 0.
Building CPU table for configuration: 68000 24-bit
1883 CPU functions
Building CPU, 44316 opcodes (0 0 1)
CPU=68000, FPU=0, MMU=0, JIT=CPU=0.
Reset at 00000000. Chipset mask = 00000000
00000000    2048K/4 =     512K Chip memory
00200000    8192K/0 =    8192K <none>
00A00000    2048K/0 =    2048K CIA
00C00000     512K/1 =     512K Slow memory
00C80000    1024K/0 =    1024K Custom chipset
00D80000     256K/0 =     256K <none>
00DC0000      64K/0 =      64K Battery backed up clock (none)
00DD0000      64K/0 =      64K <none>
00DE0000     128K/0 =     128K Custom chipset
00E00000     512K/2 =     256K Kickstart ROM (C4F0F55F)
=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
00E80000      64K/0 =      64K Autoconfig
00E90000     960K/0 =     960K <none>
00F80000     512K/2 =     256K Kickstart ROM (C4F0F55F)
=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
Segmentation fault: 11
```

**Comment by rsn8887** [comment]
I have a fix for osx, will apply after merge.

**Comment by aboutafter** [comment]
Is the CHD support still coming?

**Comment by sonninnos** [comment]
Sure, but no promises when.

**Pull request merged**
