### PR TITLE
README: fix inaccuracy regarding PUAE base ver

### PR DESCRIPTION
**Pull request by rofl0r**
plus add a link to the commit
(as i was the last contributor to and have the most up-to-date version of the
original repo before it disappeared, i think it's fair to link to my repo)

### CODE REVIEW

**Comment by sonninnos** [comment]
Not correct. This version is not that beta version, and it is not 2.6.1 anymore either, since it has a lot of code from 4.4.0.

**Comment by rofl0r** [comment]
> Besides I already have 4.5.0 and 4.9.0 rebased

you're refering to WinUAE ? quite a feat, as i was biting my teeth off trying to convert the idiomatic C++ code added to 2.9.0ish to C.

**Comment by sonninnos** [comment]
Sure, my repo has a branch called "next" which is 4.5.0b17, and indeed converted to C.

**Comment by sonninnos** [comment]
Closing due to not being relevant anymore.

**Pull request closed without merging**
