### PR TITLE
SuperHires, filename tags, retrodep+makefile streamlining

### PR DESCRIPTION
**Pull request by sonninnos**
Makefile changes:
- Better use of Makefile.common
- Duplicate (regular+jni) UAE `CFLAGS` combined to general `sysconfig.h`
- Relocated retrodeps to `retrodep`

Other:
- `CD32` + `AmigaCD` tags added for filename matching A1200 model (works for LHAs, not CDs)
- Super-High Resolution option for proper hi-res Super Skidmarks
- `vsynctimebase` minimized to match UAE warp mode
  - Improves fastforwarding somewhat

### CODE REVIEW

**Comment by WindyWinston** [comment]
Nice ! Its a shame that Super HiRes can't be changed automatically and without a restart. I think Super Stardust also uses it for the intro stars (there is a whdload option to use normal HiRes).

**Comment by sonninnos** [comment]
I had no idea, indeed it does:

SuperHires:
retroarch_2020_02_08_18_08_05_108

SuperHires + CUSTOM5=1:
retroarch_2020_02_08_18_18_36_991

Hires:
retroarch_2020_02_08_18_05_41_094

Lores:
retroarch_2020_02_08_18_06_17_596

**Comment by rsn8887** [comment]
Thanks!

**Comment by WindyWinston** [comment]
I just tried Super Hires on Android and just get a black screen. I can hear the game audio in the background.

**Comment by sonninnos** [comment]
Hard to say without any logs, maybe the used shader don't like big resolutions..?

**Pull request merged**
