### PR TITLE
Restore A600 Kickstart 3.1

### LINKED ISSUE #98: A600 WHDLoad support
Hi @sonninnos 

In #92 the default rom for A600 was changed to Kickstart 2.05 (37.300) :

|Name|Description|System|MD5|
|---|---|---|---|
|kick37300.A600|Kickstart v2.05 (Rev. 37.300)|Amiga 600|fa4acc75b49e880679fe02716af24d71|

It's the original A600 rom but it is incompatible whith WHDLoad.

Could you please re-add a configuration with the Kickstart 3.1 rom for A600 (40.063) :

|Name|Description|System|MD5|
|---|---|---|---|
|kick40063.A600|Kickstart v3.1 (Rev. 40.063)|Amiga 600|e40a5dfb3d017ba8779faba30cbd1c8e|

This configuration could be named 'A60031' for exemple.

Alternatively, the 2.05 configuration could be named 'A600ORIGINAL' and the 3.1 'A600' as before.

Regards

### PR DESCRIPTION
**Pull request by sonninnos**
Sorry for the hassle.

Closes #98

### CODE REVIEW

**Comment by MajorWilly** [comment]
No hassle whatsoever ! You're the reason this core is now brilliant !

I think the readme needs updating for the A600 (Model and Kickstarts required). And games that need a specific model section with (512k) in the filename.

**Comment by sonninnos** [comment]
Sweet. I updated the README some more.

**Comment by rsn8887** [comment]
Thanks merging. I will update the info file later today.

**Comment by DamsRoxxx** [comment]
Thanks a lot @sonninnos & @rsn8887 

Keep up the very good work with this core. I'm happy to see proficients devs take care of it.

Regards

**Pull request merged**
