### PR TITLE
VKBD updates, CD turbo speed backport

### PR DESCRIPTION
**Pull request by sonninnos**
VKBD updates:
- Themes: (Classic, CD32, Dark, Light)
retroarch_2020_03_27_17_56_56_132
- RetroPad Y = CapsLock
- Font finetuning

Bonus:
- Refined face button option labels
- Backported CD turbo speed + core option: (1x, Turbo)

### CODE REVIEW

**Comment by jdgleaver** [comment]
The VKBD update is gorgeous enough, but this:

> Backported CD turbo speed + core option: (1x, Turbo)

...this is fantastic! Excellent work, as always  :)

**Comment by sonninnos** [comment]
Sweet! The idea for the turbo came just out of nowhere while skimming through the core options ("Hmm, wasn't there a speed option in WinUAE somewhere"), and since it seemed and was a very minor undertaking to bring to this version, why not indeed to complement the floppy speed option.

And it seems to make a rather decent improvement, plus haven't found problems yet.

**Comment by jdgleaver** [comment]
I remember quite a few years ago (when I had a windows machine!) that the one and only game that *didn't* work with WinUAE's turbo option was James Pond 2. I'll certainly give that one a test tomorrow  :)

**Comment by jdgleaver** [comment]
Yes, just tested the James Pond games, and it's as I remembered. With CD turbo enabled:

- James Pond 2 does work, but the FMV runs at super speed
- James Pond 3 hangs at the intro FMV

But these are minor nothings. Everything else runs great, including the other FMV games I tried. It makes a *huge* difference to loading times!  :+1:

**Comment by sonninnos** [comment]
Thanks for confirming. Maybe there are some inbetween values between 0 and 100 (once implemented) that could fix those, like floppy integer speeds fixes many which turbo breaks.

**Comment by rsn8887** [comment]
Awesome, thanks! Merging...

**Pull request merged**
