### PR TITLE
Expose chip RAM

### PR DESCRIPTION
**Pull request by leiradel**
Exposes the chip RAM as system RAM for cheats and achievements.

### CODE REVIEW

**Comment by sonninnos** [comment]
Cool. Perhaps that env set should be in `retro_init()` with the other ones, for clarity, since:
> * Can be called from retro_init and retro_load_game.

**Comment by leiradel** [comment]
> Perhaps that env set should be in `retro_init()`

Some cores only allocate the required memory after they're given the actual content, that's why I've put it in `retro_load_game`.

I'm not saying that this is the case with P-UAE, only that it was a safe bet.

**Comment by sonninnos** [comment]
Oh ok, as long as it works then.

**Comment by leiradel** [comment]
> And shouldn't this be added too?

Sorry, forgot to answer that question. I don't think this env call is relevant anymore. @twinaphex ?

**Pull request merged**
