### PR TITLE
Added M3U and Disk control support

### PR DESCRIPTION
**Pull request by DamsRoxxx**
This core now support the usage of M3U file and disk control from within RetroArch for multi disk games.

Documentation was updated.

Build on Linux was also fixed.

### CODE REVIEW

**Comment by DamsRoxxx** [comment]
Hi @twinaphex,

Sorry to bother you. 

Could you merge this pull request to fix the linux build ?

**Comment by goedzo** [comment]
I have a question about disk-swapping. I see you have worked on this, and am curious if you support multidisk configured in uae files. So for example I have the following configuration in my uae file:

> floppy0=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(AGA)(De)(Disk 1 of 4)(A)[cr].adf
floppy1=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(AGA)(De)(Disk 2 of 4)(B)[cr].adf
floppy2=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(AGA)(De)(Disk 4 of 4)(D)[cr].adf
floppy3=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(De)(Disk 1 of 3)(A).adf
floppy4=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(De)(Disk 1 of 3)(A)[cr].adf
floppy5=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(De)(Disk 2 of 3)(B).adf
floppy6=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(De)(Disk 3 of 3)(C).adf
floppy7=./././../../Roms/Commodore - Amiga/1869 - Erlebte Geschichte Teil I (1992)(Flair)(De)(Disk 3 of 3)(C)[a savegame].adf


It would be great if that info is used to act as a playlist for diskswapping. In order to generate thes uae files, I actually created a little excel tool that generates all the UAE files from a folder where adf files can be found.
If you are interested in this tool, you can download it here:
https://www.dropbox.com/s/n7sznzmivjcm7zz/_Commodore%20-%20Amiga_uae%20generator.zip?dl=0

Just unpack the zip in a folder with adf files.
Run _list.bat to generate _output.txt. Then open the text file and past the contents in the firs row. Check if the formula's on the other columns still generate output.
Then run the macro and all the .uae config files are generated :)


BTW, you need to be able to understand VBA a little, because I hardcoded the paths in it :).

**Comment by DamsRoxxx** [comment]
Actually, disk swapping only work with m3u file. 

Give it a try and tell me. 

With m3u, UAE configuration file is automatically generated, you don't have to write a specific one 

You can see the doc in the readme in my repo at https://github.com/DamsRoxxx/libretro-uae  (it will be merged with #34).

I Could implement disk swapping with UAE files. Will look at this next week.

**Comment by DamsRoxxx** [comment]
Thanks to @bparker06 travis build for PR is now fixed!

This PR build correctly and Linux build is fixed.

Edited my description to reflect that.

**Comment by goedzo** [comment]
fixes #35 
fixes #26 

Please merge :)

**Comment by DamsRoxxx** [comment]
Hi @twinaphex @libretro,

Sorry to bother you.

Could you please merge this pull request to fix the linux build ?

**Comment by DamsRoxxx** [comment]
Hi @twinaphex,

Sorry to bother you again. Is there any problem with this PR ?

It was tested from a personnal build by some users of the forum with no problems (others than a lot of enhancement request for other parts of the core)

I have other fixes or enhancements to merge after this one.

Hope you don't have too much work with all these project management...

Anyway, keep the very good work with RetroArch 👍

**Comment by DamsRoxxx** [comment]
Hi @twinaphex,

Sorry to bother you again and again.

This PR also fix the linux and *nix build I unfortunatly broke in #30.

With the Buildbot crash of this weekend the core in nightly is very old (backup I think) for many platforms.

Thanks in advance.

**Comment by twinaphex** [comment]
@DamsRoxxx OK, let's merge it then.

**Comment by DamsRoxxx** [comment]
Many thanks @twinaphex ;-)

**Pull request merged**
