### PR TITLE
Rewrite libretro m68k.h and m68kops.h to use non-libretro variants

### PR DESCRIPTION
**Pull request by phcoder**
They encapsulate per-cpu optimizations. There is no reason to
have a version for libretro

### CODE REVIEW

**Comment by sonninnos** [comment]
As that analyze suggests, building is now very messy with those `implicit declaration`s compared to 0 warnings before. But not only that, as Windows won't build at all anymore.

`ld` spits out a ton of `undefined reference`s to `optflag_*`

**Comment by phcoder** [comment]
I believe it's a problem with analysis. Do you have windows compile log?

**Comment by sonninnos** [comment]
All right, green light from Windowsburg!

**Comment by rsn8887** [comment]
Tested on Switch and Vita, too. Works fine, same fps as before.

**Pull request merged**
