### PR TITLE
Button layout according to Retro Standards

### PR DESCRIPTION
**Pull request by sonninnos**
And a transparency toggle of some kind for the vkbd as a bonus.

Also removed the joy/mouse-toggle from GUI and made it automatic.

### CODE REVIEW

**Comment by rsn8887** [comment]
Awesome, thanks!

**Comment by MajorWilly** [comment]
@sonninnos I haven't updated yet, still waiting for the buildbot. I'm curious to know about this automatic mouse. What happens when you have a game that accepts mouse or joystick to control, like Indianapolis 500 ? I'm using a handheld that has joypad controls so will it default to mouse controls (which needs changing sensitivity) ?

Also, did you know that (with default controls) the Right Analogue Stick controls the mouse !?

**Comment by sonninnos** [comment]
That change only applies to the GUI (which has very little or no use anymore), and the regular mouse already does this, as in if you move an actual physical mouse, it always works. So it changes nothing on the RetroPad mapping.

And sure I know about the right stick, I tweaked its sensitivity a bit lately. Only thing missing from that is to be able to press the mouse buttons without changing the retromode.

**Comment by MajorWilly** [comment]
I understand now. I never realised there was a GUI ! It looks the same as Hatari which is the only part I saw on that core as it doesn't work on Android. No great loss as we now have this far superior Amiga core ! Thanks.

**Pull request merged**
