### PR TITLE
Allow uae config file to be given as argc

### PR DESCRIPTION
**Pull request by goedzo**
Merged fix from https://github.com/r-type/libretro-uae

### CODE REVIEW

**Comment by goedzo** [comment]
Fixes #36

**Comment by DamsRoxxx** [comment]
Need #34 to actually fix Linux build

**Comment by DamsRoxxx** [comment]
Hi @goedzo,

As I said in #35, if you are on windows, could you please test my core version. It's a build of #34 for windows x64 waiting to be merged.

Loading a uae file work well for me with current master (and in #34) without you're changes.

[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/2364079/puae_libretro.zip)

**Comment by goedzo** [comment]
Yes, your fix works! So this PR is no longer required.

**Pull request closed without merging**
